--- #YAML:1.0
name:                SMS-Send-AQL
version:             0.01
abstract:            SMS::Send driver to send messages via AQL (www.aql.com)
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    SMS::AQL:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Precious <davidp@preshweb.co.uk>
